name: "Greet contributor"
on:
  pull_request:
    types: [opened]
jobs:
  GreetCommitter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greet contributor"
        uses: ibakshay/greet-contributors-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          content: |
            <br/>
            Thank you for opening a PR! Please make sure that:
            <br/>
            <ul>
            <li>The title and description of the PR convey what the change is about, by mentioning a ticket for instance.</li>
            <li>The commits messages [follow the convention](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary), so your PR can be merged.</li>
            </ul>
            <br/>

